version: "3.9"
services:
  web:
    container_name: Web
    build: ./angular
    ports:
      - "4200:4200"
    networks:
      - connect
    environment:
      API_URL: "http://api:5000"
  api:
    container_name: Api
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - connect

networks:
  connect:
